---
# handlers file for cisco_prerequisites
#
- name: motd_banner_handler
  ansible.builtin.debug:
    msg: "motd banner handler Setup"

- name: user_handler
  ansible.builtin.debug:
    msg: "User Cisco Handler"
