---
- name: Initialize LDAPS Certificate
  hosts: localhost
  vars:
    cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
    root_ldaps_cert_file: "{{ root_ldaps_cert_file }}"
    intermediate_cert_files: "{{ intermediate_cert_file }}"
  tasks:
    - name: Initialize LDAPS Certificate
      dellemc.apexcp_azure.dell_apexcp_azure_initialize_ldaps_cert:
        cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
        root_ldaps_cert_file: "{{ root_ldaps_cert_file }}"
        intermediate_cert_files: "{{ intermediate_cert_files }}"
      register: initialize_ldaps_cert_result

    - name: Get Initialize LDAPS Certificate Result
      ansible.builtin.debug:
        msg: "{{ initialize_ldaps_cert_result }}"
