---
- name: Node LTP registration
  hosts: localhost
  vars:
    day1_json_file: "{{ day1_json_file }}"
  tasks:
    - name: Perform LTP registration for specified nodes
      dellemc.apexcp_azure.dell_apexcp_azure_ltp_registration:
        day1_json_file: "{{ day1_json_file }}"
      async: 7200
      poll: 0
      register: ltp_registration_status
    - name: Check if LTP registration job is completed
      ansible.builtin.async_status:
        jid: "{{ ltp_registration_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 60
    - name: Get LTP registration result
      ansible.builtin.debug:
        msg:
          - "changed: {{ job_result['changed'] }}"
          - "failed: {{ job_result['failed'] }}"
          - "msg: {{ job_result['msg'] }}"
          - "os_provision_result: {{ job_result['ltp_registration_result'] }}"
