---
- name: System Initialize
  hosts: localhost
  vars:
    primary_host_ip: "{{ primary_host_ip }}"
    day1_json_file: "{{ day1_json_file }}"
    cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
    root_ldaps_cert_file: "{{ root_ldaps_cert_file }}"
    intermediate_cert_files: "{{ intermediate_cert_file }}"
  tasks:
    - name: Install Azure Stack HCI OS on specified nodes
      dellemc.apexcp_azure.dell_apexcp_azure_system_os_provision:
        primary_host_ip: "{{ primary_host_ip }}"
        day1_json_file: "{{ day1_json_file }}"
      async: 7200
      poll: 0
      register: os_provision_status
    - name: Check if OS provision job is completed
      ansible.builtin.async_status:
        jid: "{{ os_provision_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 60
    - name: Get OS provision result
      ansible.builtin.debug:
        msg:
          - "changed: {{ job_result['changed'] }}"
          - "failed: {{ job_result['failed'] }}"
          - "msg: {{ job_result['msg'] }}"
          - "os_provision_result: {{ job_result['os_provision_result'] }}"

    - name: Initialize LDAPS Certificate
      dellemc.apexcp_azure.dell_apexcp_azure_initialize_ldaps_cert:
        cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
        root_ldaps_cert_file: "{{ root_ldaps_cert_file }}"
        intermediate_cert_files: "{{ intermediate_cert_files }}"
      register: initialize_ldaps_cert_result

    - name: Get Initialize LDAPS Certificate Result
      ansible.builtin.debug:
        msg: "{{ initialize_ldaps_cert_result }}"

    - name: Perform LTP registration for specified nodes
      dellemc.apexcp_azure.dell_apexcp_azure_ltp_registration:
        day1_json_file: "{{ day1_json_file }}"
      async: 7200
      poll: 0
      register: ltp_registration_status
    - name: Check if LTP registration job is completed
      ansible.builtin.async_status:
        jid: "{{ ltp_registration_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 60
    - name: Get LTP registration result
      ansible.builtin.debug:
        msg:
          - "changed: {{ job_result['changed'] }}"
          - "failed: {{ job_result['failed'] }}"
          - "msg: {{ job_result['msg'] }}"
          - "ltp_registration_result: {{ job_result['ltp_registration_result'] }}"

    - name: Configure and deploy a new APEX Cloud Platform cluster for Azure
      dellemc.apexcp_azure.dell_apexcp_azure_cluster_deployment:
        day1_json_file: "{{ day1_json_file }}"
      async: 36000
      poll: 0
      register: cluster_deployment_status
    - name: Check if cluster deployment job is completed
      ansible.builtin.async_status:
        jid: "{{ cluster_deployment_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 600
      delay: 60
    - name: Get cluster deployment result
      ansible.builtin.debug:
        msg:
          - "changed: {{ job_result['changed'] }}"
          - "failed: {{ job_result['failed'] }}"
          - "msg: {{ job_result['msg'] }}"
          - "cluster_deployment_result: {{ job_result['cluster_deployment_result'] }}"
